### ISSUE TITLE
User Select Theme

### ISSUE THREAD

**Issue by mauwiks** [VPTOfficial/VistaPanel-Themes#2]
I believe when using the customization of vPanel Themes, we are setting a permanent vPanel theme for the users. Please correct if I'm wrong. If so, is there a way to let the users select certain theme of his own liking? Just like in cPanel.

**Comment by mauwiks** [comment]
Hi @PCTipsGR,

Negative at my end yet, and thanks for the clarification by the way. This will be a great feature but please don't get pressured.

**Comment by yagizhan49** [comment]
> We have plans for developing a theme selector.
> 
> If you have ready code for that, said a PR and we will review it.

Seems great. As i said before, we really need a theme selector

**Comment by mahofficial** [comment]
> I believe when using the customization of vPanel Themes, we are setting a permanent vPanel theme for the users. Please correct if I'm wrong. If so, is there a way to let the users select certain theme of his own liking? Just like in cPanel.

Till we have a theme creator you can use different domains from freenom and then change themes for different domain which will allow you to let your users login to cPanel with the theme of their choice. It's just a simple trick until we create this script.

**Comment by mauwiks** [comment]
Great idea! Salut

**Comment by mahofficial** [comment]
> Great idea! I salute you

Thanks

**Comment by PCTipsGR** [comment]
I believe this is now possible with [VistaPanel-Customisations/theme-switcher](https://github.com/VPTOfficial/VistaPanel-Customizations/tree/master/theme-switcher).
