### ISSUE TITLE
Themes do not display icons correctly

### ISSUE THREAD

**Issue by PCTipsGR** [VPTOfficial/VistaPanel-Themes#3]
Some themes like Dark and Lite are not displaying icons correctly and are missing some icons like the "Closed Support Tickets" one.
These are the only themes I have tested, we need to check the behaviour of other themes too.

**Comment by PCTipsGR** [comment]
No need actually, my friend, as I have already set up a testing branch. I created this PR as a reference only.

BTW do not merge now, I have still some changes to do tomorrow.

**Comment by arcenas090** [comment]
Haha OK, my friend.
